In [7]:
import numpy as np

from dwave_qbsolv import QBSolv
import sys
sys.path.append("../src")
import utils

In [2]:
# simple 1 solution -> 2 solution perturbation problem
def qubo_alpha(a):
    q = np.array([
        [-24 + 2*a, -12 + 2*a],
        [-12 + 2*a, -24 + 2*a]
    ])
    return q

In [3]:
qbs = QBSolv()

/tmp/ipykernel_63857/3150238305.py:1: DeprecationWarning: QBSolv is deprecated as of the end of 2021 and support will be discontinued after March 2022. Please update your code to use dwave-hybrid or Leap's quantum-classical hybrid solvers instead.
  qbs = QBSolv()


In [4]:
alpha = 0
Q = qubo_alpha(alpha)
Q

array([[-24, -12],
       [-12, -24]])

In [9]:
qd = utils.array2dict(Q)

In [10]:
qbs.sample_qubo(qd)

SampleSet(rec.array([([1, 1], -72., 51)],
          dtype=[('sample', 'i1', (2,)), ('energy', '<f8'), ('num_occurrences', '<i8')]), Variables([0, 1]), {}, 'BINARY')

In [20]:
for alpha in np.linspace(2.386*10**-7, 2*10**-7, 10):
    Q = qubo_alpha(alpha)
    Q = utils.array2dict(Q)
    res = qbs.sample_qubo(Q)
    print(res.record['sample'])

[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]
[[1 1]]


In [29]:
H = np.array([[-6, 3],[3, -6]])
H = utils.array2dict(H)
H

{(0, 0): -6, (0, 1): 3, (1, 0): 3, (1, 1): -6}

In [42]:
alpha = 0.01
h = {0: -6, 1: -6}
# J = {(0,1): (6-alpha)}
J = {(0,1): (6-alpha), (0,0): -1, (1,1): -1}

qbs.sample_ising(h, J)

SampleSet(rec.array([([1, 1], -8.01, 51)],
          dtype=[('sample', 'i1', (2,)), ('energy', '<f8'), ('num_occurrences', '<i8')]), Variables([0, 1]), {}, 'SPIN')